### ISSUE TITLE
Add `README` file for project

### ISSUE THREAD

**Issue by Drit-team** [drit-group/Dr_Video#1]
Hello guys, can anyone help us providing a readme file? 
We need some badges in the top of the file, for example, both starts and forks, or other interesting badges you can think of.
Please also add some other necessary information like submit issue, add question, etc...

If you can help us, please leave a comment.

**Comment by ManasBhilare** [comment]
I would like to work on this issue.

**Comment by Grphq1** [comment]
Hello dear @Drit-team, could I work on this issue?
This is my first contribution for Hacktoberfest and I really glad to work on it.

I'm too poor, I don't have clothes so winning a T-Shirt from Hacktoberfest is the only way to get away from catching cold in this freezing Fall 😂😂 (( Just kind'a kidding 🥲 ))

**Comment by Drit-team** [comment]
Oh, its a hard choice at all 😅😂
Which one should I choose? 
Actually it's so hard to answer, but I think it's better to assign this issue to @lorem10 because its his first contribution in open source world. 

@Manas146, Could you help us on providing a `Contributing.md` file to this project? (Please see #2)

**Comment by ManasBhilare** [comment]
@Drit-team yeah sure :)
All the best @lorem10

**Comment by Grphq1** [comment]
thank you
