### ISSUE TITLE
Add `Contributing` file to this project.

### ISSUE THREAD

**Issue by Drit-team** [drit-group/Dr_Video#2]
Hello, we need help on providing a `Contributing.md` file to this project. 
You can use templates like [this](https://gist.github.com/PurpleBooth/b24679402957c63ec426).

**Comment by nkhandelwal07** [comment]
Can I do this?

**Comment by ghost** [comment]
could i work on this?

**Comment by ManasBhilare** [comment]
@Drit-team can i please work on this?
as lorem got the 1 task of readme file!
could you please assign it to me.

**Comment by Drit-team** [comment]
Hello @Manas146, Yes of course! I assign this issue to you. 
You can work on it from now, leave a comment if you need any help! Our team will help you if you want. 
We're so happy you are contributing to this project. 

Send a PR when you're done. Good luck!

**Comment by Drit-team** [comment]
> could I work on this?

Hello @BlizZard-bot, Sorry as I said in #1, this issue is for @Manas146. 
If you're keen on contributing on this project, you can work on #3 (I'm adding this 😅, please wait).

**Comment by ManasBhilare** [comment]
Thank you @Drit-team .
It should be in the same format as the above linked file, right?

**Comment by Drit-team** [comment]
> Thank you @Drit-team . It should be in the same format as the above linked file, right?

@Manas146 Your welcome, 
No it's just an example of `CONTRIBUTING` file, you can edit file and also structure at your taste.

**Comment by Drit-team** [comment]
Closed due to accepting #4
